-- ============================================================================
-- E2B(R2) ICSR Ingestion - Database Setup
-- ICH E2B(R2) compliant XML parser tables for Individual Case Safety Reports
-- ============================================================================

-- Step 1: Create Database and Schema
CREATE DATABASE IF NOT EXISTS HCLS_DEMO;
CREATE SCHEMA IF NOT EXISTS HCLS_DEMO.PHARMACOVIGILANCE;
CREATE SCHEMA IF NOT EXISTS HCLS_DEMO.STREAMLIT_APPS;

USE DATABASE HCLS_DEMO;
USE SCHEMA PHARMACOVIGILANCE;

-- ============================================================================
-- Step 2: Create E2B ICSR Tables
-- ============================================================================

-- E2B ICSR Cases: Main safety report information
CREATE TABLE IF NOT EXISTS E2B_ICSR_CASES (
    CASE_ID VARCHAR(100) PRIMARY KEY,
    SAFETY_REPORT_VERSION VARCHAR(10),
    TRANSMISSION_DATE VARCHAR(20),
    REPORT_TYPE VARCHAR(50),
    SERIOUS VARCHAR(5),
    SERIOUSNESS_DEATH VARCHAR(5),
    SERIOUSNESS_LIFE_THREATENING VARCHAR(5),
    SERIOUSNESS_HOSPITALIZATION VARCHAR(5),
    SERIOUSNESS_DISABILITY VARCHAR(5),
    SERIOUSNESS_CONGENITAL VARCHAR(5),
    SERIOUSNESS_OTHER VARCHAR(5),
    RECEIVE_DATE VARCHAR(20),
    RECEIPT_DATE VARCHAR(20),
    SENDER_ORGANIZATION VARCHAR(200),
    RECEIVER_ORGANIZATION VARCHAR(200),
    CASE_NARRATIVE TEXT,
    REPORTER_COUNTRY VARCHAR(10),
    QUALIFICATION VARCHAR(50),
    PATIENT_AGE VARCHAR(20),
    PATIENT_SEX VARCHAR(20),
    PATIENT_WEIGHT VARCHAR(20),
    PATIENT_MEDICAL_HISTORY TEXT,
    PATIENT_DEATH_DATE VARCHAR(20),
    INGESTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- E2B ICSR Drugs: Drug information per case
CREATE TABLE IF NOT EXISTS E2B_ICSR_DRUGS (
    CASE_ID VARCHAR(100),
    DRUG_SEQ INT,
    DRUG_CHARACTERIZATION VARCHAR(50),  -- Suspect, Concomitant, Interacting
    MEDICINAL_PRODUCT VARCHAR(500),
    GENERIC_NAME VARCHAR(500),
    BATCH_NUMBER VARCHAR(100),
    AUTHORIZATION_HOLDER VARCHAR(200),
    DOSAGE_TEXT VARCHAR(200),
    DOSAGE_FORM VARCHAR(100),
    ROUTE_OF_ADMIN VARCHAR(100),
    INDICATION VARCHAR(500),
    START_DATE VARCHAR(20),
    END_DATE VARCHAR(20),
    ACTION_TAKEN VARCHAR(100),
    PRIMARY KEY (CASE_ID, DRUG_SEQ)
);

-- E2B ICSR Reactions: Adverse event information per case
CREATE TABLE IF NOT EXISTS E2B_ICSR_REACTIONS (
    CASE_ID VARCHAR(100),
    REACTION_SEQ INT,
    MEDDRA_PT VARCHAR(500),
    MEDDRA_PT_CODE VARCHAR(20),
    MEDDRA_LLT VARCHAR(500),
    START_DATE VARCHAR(20),
    END_DATE VARCHAR(20),
    OUTCOME VARCHAR(100),
    PRIMARY KEY (CASE_ID, REACTION_SEQ)
);

-- ============================================================================
-- Step 3: Create Summary View
-- ============================================================================

CREATE OR REPLACE VIEW V_E2B_CASE_SUMMARY AS
SELECT 
    c.CASE_ID,
    c.REPORT_TYPE,
    c.PATIENT_AGE || ' ' || c.PATIENT_SEX AS PATIENT,
    c.SERIOUS AS IS_SERIOUS,
    d.MEDICINAL_PRODUCT AS SUSPECT_DRUG,
    d.GENERIC_NAME,
    d.INDICATION,
    LISTAGG(DISTINCT r.MEDDRA_PT, ', ') AS ADVERSE_EVENTS,
    c.REPORTER_COUNTRY,
    c.SENDER_ORGANIZATION,
    c.INGESTION_TIMESTAMP
FROM E2B_ICSR_CASES c
LEFT JOIN E2B_ICSR_DRUGS d ON c.CASE_ID = d.CASE_ID AND d.DRUG_CHARACTERIZATION = 'Suspect'
LEFT JOIN E2B_ICSR_REACTIONS r ON c.CASE_ID = r.CASE_ID
GROUP BY c.CASE_ID, c.REPORT_TYPE, c.PATIENT_AGE, c.PATIENT_SEX, c.SERIOUS,
         d.MEDICINAL_PRODUCT, d.GENERIC_NAME, d.INDICATION, c.REPORTER_COUNTRY, 
         c.SENDER_ORGANIZATION, c.INGESTION_TIMESTAMP;

-- ============================================================================
-- Step 4: Create Stage
-- ============================================================================

CREATE STAGE IF NOT EXISTS HCLS_DEMO.STREAMLIT_APPS.E2B_INGESTION_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Stage for E2B(R2) ICSR Ingestion Streamlit app';
